---
title: "Spatial data and analysis in R"
toc: false
output: 
  html_document: 
    theme: yeti
---
<br>
  <a href="https://www.iiasa.ac.at/staff/staff.php?type=auto&visibility=visible&search=true&login=jung"> Martin Jung</a><br>
  Ecosystems Services and Management <br> 
  International Institute for Applied Systems Analysis (IIASA), Laxenburg, Austria 
<br>

<!-- Internal CDAT workshop at IIASA  -->

Welcome to one of the first IIASA internal peer-2-peer CDAT workshops. Apart from the [lecture slides](lecture.html) this online self-learning course aims to provide you with basic knowledge about spatial datasets in R, how to load and spatially manipulate them. Altough in many instances R might not be the fastest tool to use for larger analyses, it is certainly the fastest in terms of transaction time between learning how to use a function and applying it to your own data. However we will also use R as a wrapper to load in some external tools. This course assumes that users already have basic knowledge of R.

I generally tried to avoid replicating things that are already openly available online through other resources. Thus, if you are interested in more or other training materials regarding spatial data and analyses in R, check out the [resources]('resources.html') link at the top with more examples and free self-learning tutorials.
